### ISSUE TITLE
Allow \r\n as newline separator

### ISSUE THREAD

**Issue by scheleaap** [qoomon/banking-swift-messages-java#1]
Importing a MT94x file with \r\n as line separator causes the parser to fail:

Could not accept [1] bank statements. Error messages: ['com.qoomon.banking.swift.message.exception.SwiftMessageParseException: Block 4 did not match pattern ([^\n]+)?\n((:?.\n)-) at line number 15'].

**Comment by qoomon** [comment]
fixed in release v1.2.1
