### ISSUE TITLE
 Allow empty lines at end of file

### ISSUE THREAD

**Issue by scheleaap** [qoomon/banking-swift-messages-java#2]
My editor adds an empty line at the end of a file when I save it. The parser currently does not allow empty lines at the end of a file, which is unpractical. What does the SWIFT specifications say about this?

Could not accept [1] bank statements. Error messages: ['com.qoomon.banking.swift.message.exception.SwiftMessageParseException: No characters are allowed outside of blocks, but was: '
' at line 16 at line number 16'].

**Comment by qoomon** [comment]
Hi sorry for the late response, i just forget this issue.
SWIFT does not allow empty lines at all.

**Comment by nieldw** [comment]
@qoomon does this also apply to newlines between multiple SwiftMessages in the same file?
I get the same error if there is a `\n` between the closing `}` of block 4 and the opening `{1:`.

**Comment by qoomon** [comment]
@nieldw yes no space allowed by specification, however I may can try to ignore spaces before between and after blocks.
WDYT

**Comment by nieldw** [comment]
@qoomon I have at least one real world example where the counterparty is inserting such spaces and newlines, and I don't see harm in allowing it and thereby making the parser a bit more lenient.

**Comment by qoomon** [comment]
Well then I will work on that this weekend.

**Comment by qoomon** [comment]
So I will allow empty lines before after and between blocks (`{...}`).

**Comment by qoomon** [comment]
should work in version `1.3.0`

**Comment by nieldw** [comment]
Tested, works for me!
