### ISSUE TITLE
Need to read Swift message response 

### ISSUE THREAD

**Issue by sandeep1407** [qoomon/banking-swift-messages-java#33]
Hi,
It looks nice source. Thanks! I was looking to parse response message mt103, mt202 and mt202cov and making java object(pojo class) of response for saving into database. Can you please help me how can i parse response and make java object to store into database.
Thanks 
Sandeep

**Comment by qoomon** [comment]
I think the easiest way is to take https://github.com/qoomon/banking-swift-messages-java/blob/master/src/main/java/com/qoomon/banking/swift/submessage/mt942/MT942Page.java as a starting point. Yust create a MT103Page, and MT202Page  as well.
You can send me a pull request and i will review it.

**Comment by sandeep1407** [comment]
Thanks for your response.
Did you get my point what I want to do. I want to save swift message response using java object. So I would like to know whats the easiest way to do it and how?
Cheers,

**Comment by qoomon** [comment]
Now I got it. I think easiest way is to create own pojo and use the framework mapstruct https://mapstruct.org/
