### ISSUE TITLE
I need help to with the MT103..

### ISSUE THREAD

**Issue by mmoustafa17** [qoomon/banking-swift-messages-java#39]
Could you please help me to implemenet the MT103 Page and page reader..

**Comment by qoomon** [comment]
sure I'am on vacation right now, however I can work on that end of december or early january
can you send me some documentation about mt103

**Comment by mmoustafa17** [comment]
Much appreciated, thank you very much..
will send it to, will be grateful if we could make a quick meeting when you are back from your vacation  .

**Comment by qoomon** [comment]
best documentation I found so far is http://www.iotafinance.com/en/SWIFT-ISO15022-Message-type-MT103.html

**Comment by mmoustafa17** [comment]
I need to create a new class for each field and define each field... correct?? 
![image](https://user-images.githubusercontent.com/55993445/70598262-1c0f7780-1bf3-11ea-9a8b-8c0c18810f43.png)

**Comment by qoomon** [comment]
Exactly.

**Comment by qoomon** [comment]
Have a look at `com.qoomon.banking.swift.submessage.mt940.MT940Page` from there you can start implementing.

**Comment by qoomon** [comment]
or actually `com.qoomon.banking.swift.submessage.mt940.MT940PageReader`

**Comment by qoomon** [comment]
@mmoustafa17 may you can contribute your MT103 implementation to this project?

**Comment by qoomon** [comment]
Close this issue in favour of #55 39
